name: Blueprint Engine
version: "0.1.0"
slug: blueprint_engine
description: The heavy processing engine for HA 3D Blueprint.
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
startup: application
boot: auto
hassio_api: true
hassio_role: default
image: "ghcr.io/{owner}/{arch}-addon-blueprint-engine"
ports:
  "8124/tcp": 8124 # Port for the internal API
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?